import Tomato from "../src/assets/tomato.png";
import Lemon from "../src/assets/lemon.png";
import Avacado from "../src/assets/avacado.png";
import Coconut from "../src/assets/coconut.png";

const cartItems = [
  {
    id: "1",
    title: "Tomato",
    price: "40",
    img: Tomato,
    quantity: 0,
    mrp: "50",
  },
  {
    id: "2",
    title: "Lemon",
    price: "50",
    img: Lemon,
    quantity: 0,
    mrp: "60",
  },
  {
    id: "3",
    title: "Avacado",
    price: "30",
    img: Avacado,
    quantity: 0,
    mrp: "40",
  },
  {
    id: "4",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "5",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "6",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "7",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "8",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "9",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "10",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "11",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "12",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "13",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "14",
    title: "Potato",
    price: "50",
    img: Lemon,
    quantity: 0,
    mrp: "60",
  },
  {
    id: "15",
    title: "Coconut",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "16",
    title: "Coconut16",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "17",
    title: "Coconut17",
    price: "20",
    img: Coconut,
    quantity: 0,
    mrp: "30",
  },
  {
    id: "18",
    title: "Potato18",
    price: "50",
    img: Lemon,
    quantity: 0,
    mrp: "60",
  },
  {
    id: "19",
    title: "Potato19",
    price: "50",
    img: Lemon,
    quantity: 0,
    mrp: "60",
  },
  {
    id: "20",
    title: "Potato20",
    price: "50",
    img: Lemon,
    quantity: 0,
    mrp: "60",
  },
];

export default cartItems;
